{"name": "test_raises", "status": "broken", "statusDetails": {"message": "NameError: name 'connect' is not defined", "trace": "def test_raises():\n        with pytest.raises(TypeError) as e:\n>           connect('localhost', '6379')\nE           NameError: name 'connect' is not defined\n\ntest_raises.py:6: NameError"}, "attachments": [{"name": "stdout", "source": "bd19e8a2-93a9-4b1a-bafe-66f4d50418b2-attachment.txt", "type": "text/plain"}], "start": 1658817628856, "stop": 1658817628856, "uuid": "de6de4bd-fc5c-42a1-88f9-adf24235844c", "historyId": "2041d43c6138909ed4ffdd39e92389f1", "testCaseId": "ff7cfa1bd85f0a8be1a641c08ede084f", "fullName": "test_raises#test_raises", "labels": [{"name": "suite", "value": "test_raises"}, {"name": "host", "value": "drl-dz0583"}, {"name": "thread", "value": "1753-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_raises"}]}